### ISSUE TITLE
Create Command, Query and related classes

### ISSUE THREAD

**Issue by br0wn** [taqat/tazman-backend#5]
Following the folder structure written in the README, for each Command and Query from the documentation create:

* class for Command/Query with properties as written in the documentation
* empty class for Command/Query Result
* interface for Command/Query Handler
* empty class for Command/Query Handler implementation

**Comment by shefalig972** [comment]
There is a folder with name "public" mention in structure . When we created Namespace for it. We are getting error because "public" is reserve key. Please provide other name for "public" folder.

![image.png](https://zube.io/files/taqat/750dec9f00343359ab7fb26691c255f8-image.png)

**Comment by br0wn** [comment]
@shefalig972 Use `Anonymus` instead.

**Comment by br0wn** [comment]
Partialy done, closing.
